ifeq ($(BR2_RAUC_CUSTOM_TARBALL),y)
RAUC_SITE_METHOD = file
RAUC_TARBALL = $(call qstrip,$(BR2_RAUC_CUSTOM_TARBALL_LOCATION))
RAUC_SITE = $(patsubst %/,%,$(dir $(RAUC_TARBALL)))
RAUC_SOURCE = $(notdir $(RAUC_TARBALL))
RAUC_VERSION = custom
BR_NO_CHECK_HASH_FOR += $(RAUC_SOURCE)
endif
