BINUTILS_OVERRIDE_SRCDIR = $(TOPDIR)/../gdb
GCC_INITIAL_OVERRIDE_SRCDIR = $(TOPDIR)/../gcc
GCC_FINAL_OVERRIDE_SRCDIR = $(TOPDIR)/../gcc
GDB_OVERRIDE_SRCDIR = $(TOPDIR)/../gdb
HOST_GDB_OVERRIDE_SRCDIR = $(TOPDIR)/../gdb
UCLIBC_OVERRIDE_SRCDIR = $(TOPDIR)/../uclibc-ng
LINUX_HEADERS_OVERRIDE_SRCDIR = $(TOPDIR)/../linux
LINUX_OVERRIDE_SRCDIR = $(TOPDIR)/../linux
BAREBOX_OVERRIDE_SRCDIR = $(TOPDIR)/../barebox
STRACE_OVERRIDE_SRCDIR = $(TOPDIR)/../strace
# Override to add "-custom" suffix to k1c-firmware build directory
K1C_FIRMWARE_OVERRIDE_SRCDIR = $(TOPDIR)/../k1c-linux-firmware
LIBFFI_OVERRIDE_SRCDIR = $(TOPDIR)/../libffi
