#!/bin/sh -e

umask 077

CONFIGFS_HOME=/sys/kernel/config

start() {
	printf "Starting usb gadget: "
	modprobe libcomposite
	modprobe usb_f_acm
	modprobe usb_f_ecm
	test -d $CONFIGFS_HOME || mount none $CONFIGFS_HOME -t configfs
	mkdir -p $CONFIGFS_HOME/usb_gadget/mppalinux

	cd $CONFIGFS_HOME/usb_gadget/mppalinux
	echo "0x0200" > bcdUSB
	echo "0x00"   > bDeviceClass

	echo "0x0525" > idVendor
	echo "0xa4aa" > idProduct

	mkdir -p strings/0x409
	echo "Kalray" > strings/0x409/manufacturer
	cat /proc/device-tree/model > strings/0x409/product
	serial="$(nvmem read kvx-nv-regbank0 board_id@10 | sed 's/\([^\x0]*\).*/\1/')"
	echo "$serial" > strings/0x409/serialnumber

	mkdir -p configs/c.1
	# self-powered
	echo "0xc0" > configs/c.1/bmAttributes
	echo "0"    > configs/c.1/MaxPower
	mkdir -p configs/c.1/strings/0x409
	echo "Linux-USB CDC Composite Gadget (Ethernet and ACM)" > configs/c.1/strings/0x409/configuration

	mkdir -p functions/ecm.usb0
	mkdir -p functions/acm.GS0
	ln -fs functions/ecm.usb0 configs/c.1
	ln -fs functions/acm.GS0 configs/c.1

	# enable the usb gadget on the first UDC device found
	ls /sys/class/udc/ | head -n1 > UDC

	echo "OK"
}

stop() {
	printf "Stopping usb gadget: "
	echo "" > $CONFIGFS_HOME/usb_gadget/mppalinux/UDC
	echo "OK"
}

case "$1" in
	start) start ;;
	stop)  stop  ;;
	restart|reload)  stop && start ;;
	*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
