#!/bin/sh

case "$1" in
	start|"")
		cd /usr/lib/uclibc-ng-test/test
		sh uclibcng-testrunner.sh
		;;
	stop)
		echo "nothing to do"
		;;
	*)
		echo "Usage: uclibc-ng-test {start|stop}" >&2
		exit 1
		;;
esac

