#!/bin/sh
#
# Start the coolidge k1c validation binary on ISS

# Coolval on HW is started from Robotframework. So this init script is only
# needed to run coolval on ISS.
DTMODEL="/sys/firmware/devicetree/base/model"
grep -q ISS "$DTMODEL" 2>/dev/null || exit 0 # Only run coolval on ISS

set -ex

COOLVALDIR="/opt/coolval"

run_coolval_tests() {
	for TESTNAME in "$@"; do
		echo ">>>>> $TESTNAME begin"
		"$COOLVALDIR"/run_tests -t "$TESTNAME"
		echo ">>>>> $TESTNAME succeeded"
		echo
	done
}

# Test modules
"$COOLVALDIR"/test_modules.sh

# Init huge pages for coolval
"$COOLVALDIR"/init_hugepages.sh

run_coolval_tests 'dtouchl' 'fork' 'fpu' 'hugemap' 'jmp' \
		  'jump_reg_saving' 'malloc' 'signal' 'syscall' \
		  'ttyKS0' 'wchar' 'stackprotector'

# Cleanup goes here
"$COOLVALDIR"/clear_hugepages.sh
