#!/bin/sh
#
# Start the coolidge k1c validation binary
#

# mount debugfs and activate pr_debug for kernel/module.c
# This is needed to get memory layout of module
# So that check_vmlinux.sh is able to validate kernel module relocs
mount -t debugfs none /sys/kernel/debug/
echo 'file kernel/module.c +p' > /sys/kernel/debug/dynamic_debug/control
modprobe module_tests
echo 'file kernel/module.c -p' > /sys/kernel/debug/dynamic_debug/control

# Load ext2+loop and create/mount a small ext2 file system
# in order to exercise kernel modules a bit more.
modprobe ext2
modprobe loop
dd if=/dev/zero of=ext2.raw bs=1M count=1
losetup /dev/loop0 ext2.raw
mkfs.ext2 /dev/loop0
mkdir /extmnt /extmnt2
mount -o loop -t ext2 ext2.raw /extmnt
echo "EXT2 TEST: OK" > /extmnt/msg
umount /extmnt
mount -o loop -t ext2 ext2.raw /extmnt2
cat /extmnt2/msg
umount /extmnt2
rm -rf /extmnt /extmnt2 ext2.raw

# Before launching coolval we need to enable hugepage. The test will map, write
# and read 10Mo. So we let's allocate 5 huge pages of 2Mo

echo 5 > /proc/sys/vm/nr_hugepages
mkdir -p /mnt/huge_2mb
mount -t hugetlbfs nodev /mnt/huge_2mb

# and 160 pages of 64Ko
echo 160 > /sys/kernel/mm/hugepages/hugepages-64kB/nr_hugepages
mkdir -p /mnt/huge_64kb
mount -t hugetlbfs nodev /mnt/huge_64kb -o pagesize=64K

modprobe k1c_dma_noc_test
modprobe -r k1c_dma_noc_test

# OK we are now ready to launch coolval
/bin/coolval
